server:
  applicationConnectors:
    - type: http
      port: 9000
      acceptorThreads: 2
      selectorThreads: 4
  adminConnectors:
    - type: http
      port: 9001

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
