server:
  applicationConnectors:
    - type: http
      port: 9000
      acceptorThreads: 2
      selectorThreads: 4
  adminConnectors:
    - type: http
      port: 9001
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /tmp/com/revolut/accountmanager/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /tmp/com/revolut/accountmanager/access.%d.log.gz
        archivedFileCount: 5
logging:
  appenders:
    - type : console
    - archivedFileCount: 3
      currentLogFilename: /tmp/com/revolut/accountmanager/app.log
      archivedLogFilenamePattern: /tmp/com/revolut/accountmanager/app.log-%d{yyyy-MM-dd}-%i.log.gz
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      maxFileSize: 200MB
      threshold: INFO
      timeZone: IST
      type: file
  level: DEBUG
