server:
  applicationConnectors:
    - type: http
      port: 9000
      acceptorThreads: 2
      selectorThreads: 4
  adminConnectors:
    - type: http
      port: 9001
  requestLog:
    appenders:
      - type: console
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: /var/log/com/revolut/accountmanager/app.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/com/revolut/accountmanager/app-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601}] %c: %m%n%rEx"
